// Vue/src/App.vue
<template>
  <div>
    <div class="dx-fieldset">
      <div class="dx-fieldset-header">Select State, City</div>
      <div class="dx-field">
        <div class="dx-field-label">State</div>
        <div class="dx-field-value">
          <DxSelectBox
            :data-source="states"
            value-expr="ID"
            display-expr="Name"
            @valueChanged="stateValueChanged"
          />
        </div>
      </div>
      <div class="dx-field">
        <div class="dx-field-label">City</div>
        <div class="dx-field-value">
          <DxSelectBox
            :ref="citySelectBoxRefKey"
            :data-source="cities"
            :value.sync="cityValue"
            value-expr="ID"
            display-expr="Name"
          />
        </div>
      </div>
    </div>
    <div class="dx-fieldset-header">In Form</div>
    <div class="dx-field">
      <DxForm :form-data.sync="address" @field-data-changed="fieldDataChanged">
        <DxSimpleItem
          data-field="StateID"
          editor-type="dxSelectBox"
          :editor-options="stateEditorOptions"
        >
          <DxLabel text="State"></DxLabel>
        </DxSimpleItem>
        <DxSimpleItem
          data-field="CityID"
          editor-type="dxSelectBox"
          :editor-options="cityEditorOptions"
        >
          <DxLabel text="City"></DxLabel>
        </DxSimpleItem>
      </DxForm>
    </div>
  </div>
</template>
<script>
import { DxSelectBox } from "devextreme-vue";
import DxForm, { DxSimpleItem, DxLabel } from "devextreme-vue/form";
import service from "./data.js";

const citySelectBoxRefKey = "city-select-box";

export default {
  components: {
    DxSelectBox,
    DxForm,
    DxSimpleItem,
    DxLabel
  },
  data() {
    const states = service.getStates(),
      cities = service.getCities();
    return {
      states,
      cities,
      cityValue: null,
      citySelectBoxRefKey,
      address: service.getAddress(),
      stateEditorOptions: {
        dataSource: states,
        valueExpr: "ID",
        displayExpr: "Name"
      },
      cityEditorOptions: {
        dataSource: cities,
        valueExpr: "ID",
        displayExpr: "Name"
      }
    };
  },
  methods: {
    stateValueChanged: function(e) {
      this.cityDataSource.filter(["StateID", "=", e.value]);
      this.cityDataSource.load();

      this.cityValue = null;
    },
    fieldDataChanged: function(e) {
      if (e.dataField === "StateID") {
        var cityEditor = e.component.getEditor("CityID");
        let dataSource = cityEditor.getDataSource();
        
        dataSource.filter(["StateID", "=", e.value]);
        dataSource.load();

        this.address.CityID = null;
      }
    }
  },
  computed: {
    citySelectBox: function() {
      return this.$refs[citySelectBoxRefKey].instance;
    },
    cityDataSource: function() {
      return this.citySelectBox.getDataSource();
    }
  }
};
</script>

// CS/React/src/App.js
import React, { useRef, useState, useCallback, useEffect } from "react";
import { SelectBox } from "devextreme-react";
import Form, { SimpleItem, Label } from "devextreme-react/form";

import service from "./data.js";

const states = service.getStates();
const cities = service.getCities();

const stateEditorOptions = {
  dataSource: states,
  valueExpr: "ID",
  displayExpr: "Name"
};

const cityEditorOptions = {
  dataSource: cities,
  valueExpr: "ID",
  displayExpr: "Name"
};

export default function App() {

  const [formData, setFormData] = useState(service.getAddress);
  const [stateValue, setStateValue] = useState(null);
  const [cityValue, setCityValue] = useState(null);
  const citySelectBoxRef = useRef();
  let cityDataSource = null;

  useEffect(() => {
    cityDataSource = citySelectBoxRef.current.instance.getDataSource();
  })

  const stateValueChanged = (e) => {
    cityDataSource.filter(["StateID", "=", e.value]);
    cityDataSource.load();
    setStateValue(e.value);
    setCityValue(null)
  }
  const cityValueChanged = e => {
    setCityValue(e.value);
  };
  const onFieldDataChanged = useCallback((e) => {
    if (e.dataField === "StateID") {
      let cityEditor = e.component.getEditor("CityID");
      let dataSource = cityEditor.getDataSource();
      dataSource.filter(["StateID", "=", e.value]);
      dataSource.load();
      setFormData({ ...formData, ...{ CityID: null, StateID: e.value } });
    }
  }, [])

  return (
    <div>
      <div className="dx-fieldset">
        <div className="dx-fieldset-header">Select State, City</div>
        <div className="dx-field">
          <div className="dx-field-label">State</div>
          <div className="dx-field-value">
            <SelectBox
              dataSource={states}
              valueExpr="ID"
              displayExpr="Name"
              value={stateValue}
              onValueChanged={stateValueChanged}
            />
          </div>
        </div>
        <div className="dx-field">
          <div className="dx-field-label">City</div>
          <div className="dx-field-value">
            <SelectBox
              ref={citySelectBoxRef}
              dataSource={cities}
              onValueChanged={cityValueChanged}
              valueExpr="ID"
              displayExpr="Name"
              value={cityValue}
            />
          </div>
        </div>
      </div>
      <div className="dx-fieldset-header">In Form</div>
      <div className="dx-field">
        <Form
          formData={formData}
          onFieldDataChanged={onFieldDataChanged}
        >
          <SimpleItem
            dataField="StateID"
            editorType="dxSelectBox"
            editorOptions={stateEditorOptions}
          >
            <Label text="State" />
          </SimpleItem>
          <SimpleItem
            dataField="CityID"
            editorType="dxSelectBox"
            editorOptions={cityEditorOptions}
          >
            <Label text="City" />
          </SimpleItem>
        </Form>
      </div>
    </div>
  );
}
